// <auto-generated />
using System;
using HotCat.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotCatCafe.MVC.Migrations
{
    [DbContext(typeof(HotCatContext))]
    [Migration("20241017145752_tableseeddata")]
    partial class tableseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotCat.Model.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HotCat.Model.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("HotCat.Model.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Coffees",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(5856),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "Consequuntur enim eaque ea qui cumque in.",
                            IsActive = true,
                            MasterId = new Guid("a731e55d-5158-43a0-8511-f4f5f9029dcb"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Teas",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(6018),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "Ullam cupiditate enim dolorem id adipisci est.",
                            IsActive = true,
                            MasterId = new Guid("a614948d-40d3-4ff6-93c4-74da0f266e54"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Cold Beverages",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(6050),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "Et aut tempore cupiditate.",
                            IsActive = true,
                            MasterId = new Guid("9fb09a34-8d64-48a7-818d-3bb0623d6912"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Breakfast",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(6063),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "Saepe quia ut ipsum.",
                            IsActive = true,
                            MasterId = new Guid("2992ad64-01ec-4127-aba7-ab162d448b3f"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Salads",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(6077),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "Dolor iusto suscipit et voluptates minima itaque.",
                            IsActive = true,
                            MasterId = new Guid("28246d4f-423a-441d-aef5-b364633134c4"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Burgers",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(6123),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "Quaerat quis est commodi qui ipsam sapiente dicta.",
                            IsActive = true,
                            MasterId = new Guid("09e2e842-4618-4510-8b64-3c34e9653041"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Pizzas",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(6143),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "At reiciendis nulla.",
                            IsActive = true,
                            MasterId = new Guid("d7a78f5c-1603-4915-911f-4acd83b4a1d6"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Desserts",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(6154),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "Reprehenderit id debitis.",
                            IsActive = true,
                            MasterId = new Guid("abefb9b8-45dc-4b1e-ab8e-90132ce67e5f"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Cakes",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(6163),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "Molestiae animi quibusdam distinctio suscipit inventore.",
                            IsActive = true,
                            MasterId = new Guid("3c9f5c9d-3a23-4dfb-8391-4aa388823036"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Ice Creams",
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 644, DateTimeKind.Local).AddTicks(6179),
                            CreatedIpAddress = "192.168.1.1",
                            Description = "Alias placeat tempora reiciendis eum aut doloremque et laboriosam dolorem.",
                            IsActive = true,
                            MasterId = new Guid("04743028-363d-4e8f-b91b-9b85ed20bbd6"),
                            Status = 0,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HotCat.Model.Entities.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OrderDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9657),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("69d95566-d403-42ea-ab9c-8935230b3d47"),
                            OrderDate = new DateTime(2023, 11, 27, 4, 54, 38, 647, DateTimeKind.Local).AddTicks(9666),
                            Status = 0,
                            TotalAmount = 379.36m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9778),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("cb331e92-e1bc-47ab-9527-1342751d9823"),
                            OrderDate = new DateTime(2024, 2, 27, 2, 55, 49, 229, DateTimeKind.Local).AddTicks(2934),
                            Status = 0,
                            TotalAmount = 20.95m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9787),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("e4609c2d-2ca5-4bd9-8a39-510dda41aa89"),
                            OrderDate = new DateTime(2024, 4, 22, 18, 17, 10, 221, DateTimeKind.Local).AddTicks(3062),
                            Status = 0,
                            TotalAmount = 141.46m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9793),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("b8507f81-e1f6-489a-8549-76a9e8464077"),
                            OrderDate = new DateTime(2024, 8, 21, 22, 58, 24, 460, DateTimeKind.Local).AddTicks(9525),
                            Status = 0,
                            TotalAmount = 127.24m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9799),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("bf849f1a-90ef-459a-a17d-9a1337fcbae6"),
                            OrderDate = new DateTime(2024, 5, 25, 23, 22, 52, 806, DateTimeKind.Local).AddTicks(9290),
                            Status = 0,
                            TotalAmount = 106.32m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9813),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("44843512-bf56-405b-a49b-8563c21366ce"),
                            OrderDate = new DateTime(2024, 6, 27, 12, 31, 6, 305, DateTimeKind.Local).AddTicks(9965),
                            Status = 0,
                            TotalAmount = 81.14m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9819),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("1458ddf0-ef15-48f4-9f58-b4af5204403d"),
                            OrderDate = new DateTime(2024, 8, 21, 9, 16, 1, 66, DateTimeKind.Local).AddTicks(7159),
                            Status = 0,
                            TotalAmount = 427.30m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9825),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("a921fd5f-c786-4a91-9b89-2bf269b16ca6"),
                            OrderDate = new DateTime(2024, 4, 8, 1, 16, 6, 108, DateTimeKind.Local).AddTicks(4443),
                            Status = 0,
                            TotalAmount = 463.13m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9830),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("ea50c314-9183-456e-87f7-aca7d1a784a2"),
                            OrderDate = new DateTime(2024, 2, 10, 23, 16, 15, 460, DateTimeKind.Local).AddTicks(2510),
                            Status = 0,
                            TotalAmount = 316.31m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9835),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("e510c7d3-a6d8-4648-b51c-442b83cf0a71"),
                            OrderDate = new DateTime(2024, 7, 4, 6, 9, 21, 59, DateTimeKind.Local).AddTicks(5156),
                            Status = 0,
                            TotalAmount = 427.51m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9840),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("955d57bf-6f70-484b-a011-439debc5205b"),
                            OrderDate = new DateTime(2024, 2, 10, 18, 29, 42, 58, DateTimeKind.Local).AddTicks(7510),
                            Status = 0,
                            TotalAmount = 60.35m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9845),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("4cd6e24f-5505-4d84-8e04-b0a3f69864d0"),
                            OrderDate = new DateTime(2024, 1, 30, 21, 14, 50, 97, DateTimeKind.Local).AddTicks(7832),
                            Status = 0,
                            TotalAmount = 258.78m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9850),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("0a0f5f53-bc56-48e2-a9dc-258909ef3122"),
                            OrderDate = new DateTime(2023, 11, 24, 5, 39, 34, 359, DateTimeKind.Local).AddTicks(1272),
                            Status = 0,
                            TotalAmount = 399.58m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9857),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("7f8f691c-edf8-48dc-a376-77810feb04e2"),
                            OrderDate = new DateTime(2024, 4, 13, 11, 52, 2, 56, DateTimeKind.Local).AddTicks(9718),
                            Status = 0,
                            TotalAmount = 243.88m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9861),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("1a3cb060-5d38-47d0-a100-65dac3f511dd"),
                            OrderDate = new DateTime(2023, 11, 18, 7, 42, 59, 286, DateTimeKind.Local).AddTicks(9232),
                            Status = 0,
                            TotalAmount = 409.33m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9867),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("addaf712-1628-4aa1-aeb9-ccca2759f7b7"),
                            OrderDate = new DateTime(2024, 7, 7, 8, 0, 45, 896, DateTimeKind.Local).AddTicks(9034),
                            Status = 0,
                            TotalAmount = 459.09m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9872),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("b7c4dd63-fa0b-4a32-a42d-5dc3f205fc92"),
                            OrderDate = new DateTime(2023, 12, 3, 1, 28, 22, 681, DateTimeKind.Local).AddTicks(1612),
                            Status = 0,
                            TotalAmount = 225.94m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9877),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("1579ed17-281e-4a72-bbd0-b48b54f8d534"),
                            OrderDate = new DateTime(2024, 1, 29, 7, 15, 38, 944, DateTimeKind.Local).AddTicks(5477),
                            Status = 0,
                            TotalAmount = 411.06m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9882),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("792df04a-762f-40f2-8ffd-a103747805ac"),
                            OrderDate = new DateTime(2024, 10, 6, 13, 15, 27, 743, DateTimeKind.Local).AddTicks(6144),
                            Status = 0,
                            TotalAmount = 73.54m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 647, DateTimeKind.Local).AddTicks(9887),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("92cc83a7-da5a-434c-b9c7-352beb12c408"),
                            OrderDate = new DateTime(2024, 5, 10, 5, 43, 43, 251, DateTimeKind.Local).AddTicks(5896),
                            Status = 0,
                            TotalAmount = 39.01m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HotCat.Model.Entities.OrderDetail", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("HotCat.Model.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("UnitsInStock")
                        .HasColumnType("smallint");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 645, DateTimeKind.Local).AddTicks(9841),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.13,
                            ImagePath = "https://picsum.photos/640/480/?image=80",
                            IsActive = true,
                            MasterId = new Guid("3e95d64b-08f9-4430-9a23-d1e85a14d6dd"),
                            ProductName = "Pie",
                            Status = 0,
                            UnitPrice = 693.97m,
                            UnitsInStock = (short)35,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(4),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.12,
                            ImagePath = "https://picsum.photos/640/480/?image=940",
                            IsActive = true,
                            MasterId = new Guid("7db08738-1b4b-4c71-a943-1e00d6ffb64e"),
                            ProductName = "Cappuccino",
                            Status = 0,
                            UnitPrice = 335.31m,
                            UnitsInStock = (short)95,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(17),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.14999999999999999,
                            ImagePath = "https://picsum.photos/640/480/?image=934",
                            IsActive = true,
                            MasterId = new Guid("c458ec87-ad94-4669-a690-347c7f660f99"),
                            ProductName = "Brownie",
                            Status = 0,
                            UnitPrice = 968.04m,
                            UnitsInStock = (short)86,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            CategoryId = 10,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(25),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.46999999999999997,
                            ImagePath = "https://picsum.photos/640/480/?image=908",
                            IsActive = true,
                            MasterId = new Guid("e08801db-1d4a-4498-88af-3bd36beaca03"),
                            ProductName = "Flat White",
                            Status = 0,
                            UnitPrice = 240.91m,
                            UnitsInStock = (short)29,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            CategoryId = 7,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(33),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.17999999999999999,
                            ImagePath = "https://picsum.photos/640/480/?image=426",
                            IsActive = true,
                            MasterId = new Guid("f963e804-53a3-44a3-992d-25e9298d669b"),
                            ProductName = "Affogato",
                            Status = 0,
                            UnitPrice = 172.77m,
                            UnitsInStock = (short)92,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(40),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.26000000000000001,
                            ImagePath = "https://picsum.photos/640/480/?image=157",
                            IsActive = true,
                            MasterId = new Guid("863dc3f0-b136-45b4-ba46-1478f8138647"),
                            ProductName = "Espresso",
                            Status = 0,
                            UnitPrice = 40.20m,
                            UnitsInStock = (short)85,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(48),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.46999999999999997,
                            ImagePath = "https://picsum.photos/640/480/?image=951",
                            IsActive = true,
                            MasterId = new Guid("e1558dfe-d932-4468-a33c-a7c33e42e470"),
                            ProductName = "Cappuccino",
                            Status = 0,
                            UnitPrice = 535.42m,
                            UnitsInStock = (short)53,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            CategoryId = 9,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(55),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.11,
                            ImagePath = "https://picsum.photos/640/480/?image=902",
                            IsActive = true,
                            MasterId = new Guid("d7cd22eb-8a78-4c74-a1f6-c183772e0800"),
                            ProductName = "Cappuccino",
                            Status = 0,
                            UnitPrice = 355.94m,
                            UnitsInStock = (short)59,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(87),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.0,
                            ImagePath = "https://picsum.photos/640/480/?image=586",
                            IsActive = true,
                            MasterId = new Guid("fd5d6c66-c42f-488c-ae0c-9e8f320b3af4"),
                            ProductName = "Espresso",
                            Status = 0,
                            UnitPrice = 429.56m,
                            UnitsInStock = (short)45,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(96),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.42999999999999999,
                            ImagePath = "https://picsum.photos/640/480/?image=289",
                            IsActive = true,
                            MasterId = new Guid("8461910a-8e7e-43aa-bc8c-6162307d4dda"),
                            ProductName = "Chocolate Fondue",
                            Status = 0,
                            UnitPrice = 361.60m,
                            UnitsInStock = (short)26,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(104),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.34000000000000002,
                            ImagePath = "https://picsum.photos/640/480/?image=376",
                            IsActive = true,
                            MasterId = new Guid("1c68c471-dcce-4afc-80d5-eb510ef08b69"),
                            ProductName = "Tiramisu",
                            Status = 0,
                            UnitPrice = 149.26m,
                            UnitsInStock = (short)95,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(111),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.33000000000000002,
                            ImagePath = "https://picsum.photos/640/480/?image=192",
                            IsActive = true,
                            MasterId = new Guid("15ab94ed-0393-42ec-85d3-3a6970beafd5"),
                            ProductName = "Macaron",
                            Status = 0,
                            UnitPrice = 59.63m,
                            UnitsInStock = (short)86,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            CategoryId = 6,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(118),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.45000000000000001,
                            ImagePath = "https://picsum.photos/640/480/?image=50",
                            IsActive = true,
                            MasterId = new Guid("2f2c2759-460d-4e5a-8475-727346b03338"),
                            ProductName = "Frappé",
                            Status = 0,
                            UnitPrice = 793.20m,
                            UnitsInStock = (short)53,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            CategoryId = 2,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(125),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.0,
                            ImagePath = "https://picsum.photos/640/480/?image=130",
                            IsActive = true,
                            MasterId = new Guid("d69bf803-5d07-42c6-8a27-5937ac848f6c"),
                            ProductName = "Brownie",
                            Status = 0,
                            UnitPrice = 683.48m,
                            UnitsInStock = (short)57,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(132),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.34999999999999998,
                            ImagePath = "https://picsum.photos/640/480/?image=184",
                            IsActive = true,
                            MasterId = new Guid("95fe6f66-6aee-43cb-ab6f-ff3e3c51d334"),
                            ProductName = "Frappé",
                            Status = 0,
                            UnitPrice = 308.90m,
                            UnitsInStock = (short)73,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16,
                            CategoryId = 3,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(139),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.40000000000000002,
                            ImagePath = "https://picsum.photos/640/480/?image=1054",
                            IsActive = true,
                            MasterId = new Guid("8916cd1e-cbb2-4f4a-984b-f59231f63684"),
                            ProductName = "Frappé",
                            Status = 0,
                            UnitPrice = 710.24m,
                            UnitsInStock = (short)42,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17,
                            CategoryId = 5,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(146),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.14999999999999999,
                            ImagePath = "https://picsum.photos/640/480/?image=740",
                            IsActive = true,
                            MasterId = new Guid("51d3ddd8-5d96-486f-b290-04ad15cd2242"),
                            ProductName = "Profiterole",
                            Status = 0,
                            UnitPrice = 69.58m,
                            UnitsInStock = (short)57,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18,
                            CategoryId = 1,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(156),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.45000000000000001,
                            ImagePath = "https://picsum.photos/640/480/?image=1068",
                            IsActive = true,
                            MasterId = new Guid("ea863934-2809-48cc-9f59-121a9b875100"),
                            ProductName = "Espresso Macchiato",
                            Status = 0,
                            UnitPrice = 574.24m,
                            UnitsInStock = (short)75,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(162),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.46000000000000002,
                            ImagePath = "https://picsum.photos/640/480/?image=251",
                            IsActive = true,
                            MasterId = new Guid("42493a17-a0c1-4459-81f5-2708ac3c3353"),
                            ProductName = "Espresso",
                            Status = 0,
                            UnitPrice = 963.90m,
                            UnitsInStock = (short)10,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20,
                            CategoryId = 4,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 646, DateTimeKind.Local).AddTicks(196),
                            CreatedIpAddress = "192.168.1.1",
                            Discount = 0.37,
                            ImagePath = "https://picsum.photos/640/480/?image=926",
                            IsActive = true,
                            MasterId = new Guid("7e4b2dde-b2a5-4016-9679-fef72b37d32c"),
                            ProductName = "Profiterole",
                            Status = 0,
                            UnitPrice = 752.96m,
                            UnitsInStock = (short)5,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HotCat.Model.Entities.Table", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6627),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("95606f45-7cdb-42a7-a03f-25a7de4f8fad"),
                            Status = 0,
                            TableName = "Deniz Kenarı 1",
                            TableNumber = "1",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6669),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("a17eb20f-d043-4ff4-a1dd-f55b8f6baa1e"),
                            Status = 0,
                            TableName = "Deniz Kenarı 2",
                            TableNumber = "2",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6674),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("8f637bf5-a956-427d-b79d-6b772b6de384"),
                            Status = 0,
                            TableName = "Deniz Kenarı 3",
                            TableNumber = "3",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6677),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("65155892-11bd-4e82-8230-6971c5847be9"),
                            Status = 0,
                            TableName = "Deniz Kenarı 4",
                            TableNumber = "4",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6679),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("5885a882-f70a-4110-9536-c534141bcdc0"),
                            Status = 0,
                            TableName = "Deniz Kenarı 5",
                            TableNumber = "5",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6683),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("2d22bf56-b8d4-4685-8829-26b1f600aaa6"),
                            Status = 0,
                            TableName = "Deniz Kenarı 6",
                            TableNumber = "6",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6686),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("81d5aa4f-9ab9-4333-a1e6-f2aeabd9bac6"),
                            Status = 0,
                            TableName = "Deniz Kenarı 7",
                            TableNumber = "7",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6689),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("8c83a0e6-c00d-4b66-aa94-bee6d6e518ba"),
                            Status = 0,
                            TableName = "Deniz Kenarı 8",
                            TableNumber = "8",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6697),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("2066750a-0093-4c41-9bb7-59ef8dab784a"),
                            Status = 0,
                            TableName = "Deniz Kenarı 9",
                            TableNumber = "9",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            CreatedComputerName = "DESKTOP-JSABNAD",
                            CreatedDate = new DateTime(2024, 10, 17, 17, 57, 52, 648, DateTimeKind.Local).AddTicks(6700),
                            CreatedIpAddress = "192.168.1.1",
                            IsActive = true,
                            MasterId = new Guid("073e9f31-d08e-4583-9325-64dd8e09a18d"),
                            Status = 0,
                            TableName = "Deniz Kenarı 10",
                            TableNumber = "10",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HotCat.Model.Entities.Order", b =>
                {
                    b.HasOne("HotCat.Model.Entities.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId");

                    b.HasOne("HotCat.Model.Entities.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId");

                    b.Navigation("AppUser");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("HotCat.Model.Entities.OrderDetail", b =>
                {
                    b.HasOne("HotCat.Model.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotCat.Model.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HotCat.Model.Entities.Product", b =>
                {
                    b.HasOne("HotCat.Model.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("HotCat.Model.Entities.AppUserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HotCat.Model.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HotCat.Model.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("HotCat.Model.Entities.AppUserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotCat.Model.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HotCat.Model.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotCat.Model.Entities.AppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HotCat.Model.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HotCat.Model.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("HotCat.Model.Entities.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("HotCat.Model.Entities.Table", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
